### PR TITLE
Communiction - Add code owners and label triggers

### PR DESCRIPTION
**Pull request by JianpingChen**

### CODE REVIEW

**Review by RezaJooyandeh — APPROVED** [review]

**Review by anuchandy — APPROVED** [review]

**Comment by JianpingChen** [comment]
Hmm, it is still "Merging is blocked". It tells me "You’re not authorized to merge this pull request." I guess I'll need to be a contributor with write access. I'm part of Azure organization already. What did I miss? @bsiegel

**Comment by bsiegel** [comment]
I double checked and you are a member of azure-sdk-write which has write access to this repo. Sometimes the permissions which cascade down from child teams seem to stop working, I'm not sure how we usually resolve that. I can merge this for you for now though.

**Pull request merged**
