### PR TITLE
Added Core Options types: ClientOptions, RequestOptions and TransportOptions

### LINKED ISSUE #314: Azure Core Options types
azure-core should contain the following interface hierarchy which will contain global configuration parameters that will be used by all clients.

azure-storage-blob should have Options objects that implement these interfaces - the client builder should accept a StorageBlobClientOptions, and each method that has options should take a per-method Options object (e.g. ListBlobsOptions, DeleteBlobOptions).

```
AzureClientOptions (Base class for client options)
└──StorageBlobClientOptions (Specific client options, passed to builder)

AzureOptions (Base class for client method options)
└──DeleteBlobOptions (Specific non-paginated client method options, passed to the client method)
```

AzureClientOptions should have at least the following members:
```java
    // The API version of the service to invoke.
    String apiVersion;
    // The `ClientLogger` to be used by the service client.
    ClientLogger logger;
    // Options for configuring telemetry sent by the service client.
    TelemetryOptions telemetryOptions;
    // Global transport options.
    TransportOptions transportOptions;
```

TelemetryOptions should have at least the following members:
```java
    // Whether platform information will be omitted from the user agent string sent by the service client.
    boolean telemetryDisabled;
    // An optional user-specified application ID included in the user agent string sent by the service client.
    @Nullable String applicationId;
```

TransportOptions should have at least the following members:
```java
    // Default timeout on any network call. -1 means no timeout. (Should this be a nullable `Double` instead?)
    double timeoutInSeconds;
    // Retry strategy.
    @Nullable RetryStrategy retryStrategy;
```

AzureOptions should have at least the following members:
```java
    // A client-generated, opaque value with 1KB character limit that is recorded in analytics logs.
    // Highly recommended for correlating client-side activities with requests received by the server.
    @Nullable String clientRequestId;
    // A token used to make a best-effort attempt at canceling a request.
    @Nullable CancellationToken cancellationToken;
```

### PR DESCRIPTION
**Pull request by vcolin7**
Fixes #314.

`TransportOptions` includes a `timeout` property, which won't be used yet by our `CancellationToken` pending some discussions about how to properly implement such a feature.

### CODE REVIEW

**Comment by vcolin7** [comment]
Not sure if we should rename `apiVersion` to `serviceVersion` instead, it appears that's what it's called in other languages. What do you think @bsiegel?

**Comment by bsiegel** [comment]
I think I agree, `apiVersion` seems like the correct name.

**Comment by vcolin7** [comment]
> 
> 
> I think I agree, `apiVersion` seems like the correct name.

Did you mean to say `serviceVersion`?

**Comment by vcolin7** [comment]
Actually, it seems that the use of `serviceVersion` and `apiVersion` is split between languages, for exmaple, for KeyVault .NET and Java use the former and Python and JS use the latter.

**Comment by vcolin7** [comment]
I think we can go with `apiVersion` for now to be consistent with iOS and change it later if we think it's necessary :) @bsiegel @anuchandy

**Comment by bsiegel** [comment]
This looks good for Core, however it doesn't fully complete #314 - that requires that we also update client libraries to use this hierarchy. As it is now, I think this is fine but it means if we compile the entire SDK locally it will fail because clients will not be updated to the new options types. Do you want to try to address that here, or should we file an issue to update the client libraries as part of a followup?

**Review by bsiegel — APPROVED** [review]

**Comment by vcolin7** [comment]
As discussed separately with @bsiegel, this change is additive for the most part and should not affect client libraries that depend on Azure Core.

**Pull request merged**
