### PR TITLE
Remove duplicate permission from manifest

### PR DESCRIPTION
**Pull request by kostasdrakonakis**

### CODE REVIEW

**Comment by kostasdrakonakis** [comment]
Solves #1206

**Review by vcolin7 — APPROVED** [review]
Looks good to me. Any thoughts @jiminwen-msft?

**Comment by kostasdrakonakis** [comment]
@vcolin7 @jiminwen-msft are we going to merge this one?

**Comment by vcolin7** [comment]
I think it's safe to merge this.

**Pull request merged**
