### PR TITLE
Implement AzurePush

### LINKED ISSUE #63: Implement AzurePush

### PR DESCRIPTION
**Pull request by ftchirou**
Thanks for taking the time to contribute. Please take a moment to fill out the information below.

Fixes #63 .

Changes Proposed in this pull request:
- Provide a clean and simple Kotlin API for [Azure Notifications Hub](https://docs.microsoft.com/en-us/azure/notification-hubs/).

### CODE REVIEW

**Comment by ftchirou** [comment]
Pending docs and tests for review.

**Comment by ftchirou** [comment]
Hey @NateRickard! I pushed my latest changes. I ported the framework from what I've done on iOS but there is an issue with the token generated not being valid on Android. Could you take a look? And review the PR? 🙏

**Comment by NateRickard** [comment]
@ftchirou Token generation should be fixed and I fixed a few other things as well.  I think there's still work to be done (the parser seems to be looking for apple registrations, for one).  I'll be OOO thru Friday so if you get a chance to dig into it let me know so I don't duplicate effort.

**Comment by bsiegel** [comment]
Closing as wontfix, we are preparing for a release of the Track 2 SDK libraries which are based on a different codebase.

**Pull request closed without merging**
